# Generated by Django 4.2.4 on 2023-08-15 04:58

from django.db import migrations, models
import django.db.models.deletion
import recipes_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0002_category_recipe_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='categories',
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(default=recipes_app.models.get_default_category, on_delete=django.db.models.deletion.CASCADE, to='recipes_app.category'),
        ),
    ]
